apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-lkse
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-lkse
    app.kubernetes.io/part-of: component-annotation-dotnet-component
  name: devfile-sample-dotnet60-basic-lkse
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-lkse
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-lkse
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rs-demos-wxdp-tenant/component-annotation-dotnet-component/devfile-sample-dotnet60-basic-lkse@sha256:4952d9d152968c415a6ceebba86643fa47b23443a6ea2273827b0be6c1e4366f
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
